#!/bin/bash

#SBATCH --job-name=fslswap
#SBATCH --ntasks-per-node=1
#SBATCH --mem=4G
#SBATCH --time=00:15:00

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Hanna Willis & Rebecca Truby 

export input=$(jq -r .input config.json)
export dimensions=`jq -r '.swap_dimensions' config.json`
export bvecs=`jq -r '.bvecs' config.json`
export dwi_sbref=`jq -r '.sbref' config.json`

# make output directory
mkdir -p out_dir

# If running diffusion data
# DTI requires dwi & bvecs (and optional sbregf)

if [ "$(basename $input)" == "dwi.nii.gz" ]; then
  fslswapdim $input $dimensions out_dir/$input
  
  # This is a Saad python script 
  bvec_swap.py $bvecs $dimensions out_dir/$bvecs
  fslswapdim $dwi_sbref $dimensions out_dir/$dwi_sbref

# Else, if not DTI then do this (input for fMRI and anat is the same - single input nifti)
else
  fslswapdim $input dimensions out_dir/$input
fi



