#!/bin/bash

#SBATCH --job-name=fslswap
#SBATCH --ntasks-per-node=1
#SBATCH --mem=4G
#SBATCH --time=00:15:00

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Hanna Willis, Rebecca Truby & Giulia Bertò

time singularity exec -e docker://brainlife/fsl:5.0.11 ./fsl.sh

   
   
   
   
   
   
   
   
   
