#!/bin/bash

#SBATCH --job-name=template
#SBATCH --ntasks-per-node=1
#SBATCH --mem=4G
#SBATCH --time=00:15:00

# Copyright (c) 2020 brainlife.io at University of Texas at Austin and Indiana University
# 
# This is the main file run by the brainlife.io orchestration system
#
# Author: Franco Pestilli

T1=`jq -r '.t1' config.json`
DIMENSIONS=`jq -r '.swap_dimensions' config.json`

# make output directory
mkdir -p out_dir

# run the actual run fslswapdim
fslswapdim T1 DIMENSIONS out_dir/t1.nii.gz
